//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phone_Directory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public Admins()
        {
            this.Departments = new HashSet<Departments>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Departments> Departments { get; set; }
    }
}
