//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phone_Directory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<int> ManagerID { get; set; }
    
        public virtual Departments Departments { get; set; }
    }
}
